# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: ls
      run: ls
    - name: ls Build dir
      run: ls /home/runner/work/CSharp-Jiyu-Killer/CSharp-Jiyu-Killer/CSharp-Jiyu-Killer/bin/Debug/net8.0/
    - name: Upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: CSharp-Jiyu-Killer.exe
        path: /home/runner/work/CSharp-Jiyu-Killer/CSharp-Jiyu-Killer/CSharp-Jiyu-Killer/bin/Debug/net8.0/CSharp-Jiyu-Killer.exe
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
